name: decrypt password.json

on: push

jobs:
  my-job:
    name: decrypt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_password.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.password_passphrase }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: cat $HOME/secrets/password.json
